name: hackon
description: "mobile application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  flutter_spinkit: ^5.2.1
  bart: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Riley
      fonts:
        - asset: assets/custom_fonts/Riley.otf
    - family: Inter
      fonts:
        - asset: assets/custom_fonts/Inter-Regular.ttf
